import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dbdad6",
        "primary-fixed": "#d1e8d9",
        "primary-container": "#2e4237",
        "secondary-fixed": "#ffdad3",
        "primary-fixed-dim": "#b5ccbd",
        "surface-variant": "#e3e2df",
        "on-secondary-fixed-variant": "#8c1800",
        "on-primary": "#ffffff",
        "on-secondary-container": "#5c0c00",
        "secondary-fixed-dim": "#ffb4a4",
        "on-primary-fixed": "#0c1f16",
        "on-tertiary-container": "#c5a0a0",
        "surface-tint": "#4e6357",
        surface: "#faf9f5",
        "on-tertiary-fixed": "#2b1516",
        outline: "#737874",
        "tertiary-container": "#523737",
        "secondary-container": "#fd5e3c",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#5c403f",
        "inverse-primary": "#b5ccbd",
        error: "#ba1a1a",
        "on-primary-container": "#98aea0",
        "surface-container": "#efeeea",
        "on-primary-fixed-variant": "#374b40",
        "surface-container-low": "#f4f4f0",
        "on-background": "#1b1c1a",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdad9",
        "tertiary-fixed-dim": "#e4bdbd",
        "on-surface-variant": "#424844",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        background: "#faf9f5",
        secondary: "#b32a0b",
        "outline-variant": "#c2c8c2",
        "inverse-surface": "#2f312e",
        "surface-container-highest": "#e3e2df",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf9f5",
        "surface-container-high": "#e9e8e4",
        "inverse-on-surface": "#f2f1ed",
        primary: "#182c22",
        "on-secondary-fixed": "#3d0600",
        "on-surface": "#1b1c1a",
        tertiary: "#3a2222",
        brand: {
          50: "#eff6ff",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          900: "#1e3a8a",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        margin: "2.5rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "23": "5.75rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-hero": ["Playfair Display", "serif"],
        "data-metric": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Playfair Display", "serif"],
        "title-editorial": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["11px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "500" }],
        "display-hero": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "data-metric": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "title-editorial": ["16px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
